#! /bin/csh

git fetch origin
git merge origin/master


#------------------------------------------------------------------------------
#   web
#------------------------------------------------------------------------------
chmod o+r *.php

chmod o+x php
chmod o+r php/*

chmod o+x css
chmod o+r css/*

chmod o+x pic
chmod o+r pic/*

chmod o+x data
chmod o+r data/*


#------------------------------------------------------------------------------
#   db
#------------------------------------------------------------------------------
chmod o+x db
chmod o+r db/*

chmod o+x schema
chmod o+r schema/*

